### ISSUE TITLE
Builder doesn't include .css files in zip file

### ISSUE THREAD

**Issue by bnylund** [olton/Metro4-Builder#2]
[metro4-4.3.7-9e25369f7f82120b177e9b2db27440cc.zip](https://github.com/olton/Metro4-Builder/files/4774905/metro4-4.3.7-9e25369f7f82120b177e9b2db27440cc.zip)

**Comment by olton** [comment]
your components set please

**Comment by bnylund** [comment]
![components](https://user-images.githubusercontent.com/31191383/84573417-ec8a2500-ad65-11ea-90b8-33d10c89d569.png)

**Comment by olton** [comment]
Fixed, please check it

**Comment by bnylund** [comment]
Fixed, thank you!
